#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)


# Parse arguments.
if [ $# -eq 0 ]; then
    echo "E: The ${name} command takes at least one argument"
    exit 1
fi

repo_install=0
while [ $# -gt 0 ]; do
    case "$1" in
        openssl-1.0.2)
            sh ${here}/manager-install-openssl 1.0.2j
        ;;
        openssl-1.1.1)
            sh ${here}/manager-install-openssl 1.1.1k
        ;;
        pyenv-dev)
            sh ${here}/manager install $(${here}/manager info pyenv-dev)
        ;;
        python-cython)
            sh ${here}/manager-install-python-cython
        ;;
        python-numpy)
            sh ${here}/manager-install-python-numpy
        ;;
        python-scipy)
            sh ${here}/manager-install-python-scipy
        ;;
        *)
            pkgman=$(sh ${here}/manager info os-package-manager)
            case ${pkgman} in
                apt-get)
                    norecommends=--no-install-recommends
                ;;
                zypper)
                    norecommends=--no-recommends
                ;;
                *)
                    norecommends=
                ;;
            esac
            if [ ${repo_install} -eq 0 ]; then
                sh ${here}/manager update
                repo_install=1
            fi
            ${pkgman} install -y ${norecommends} $1
        ;;
    esac
    shift
done

if [ ${repo_install} -eq 1 ]; then
    sh ${here}/manager clean
fi
