#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)


# Parse arguments.
if [ $# -ne 1 ]; then
    echo "E: The ${name} command takes one argument"
    exit 1
fi

case "$1" in
    openssl-1.0.2|openssl-1.1.1)
        sslpath=/usr/local/ssl
        prefix=$(sh ${here}/manager info openssl-root $(echo $1 | cut -d- -f2))
        if [ "$(readlink -f ${sslpath})" = "${prefix}" ]; then
            rm ${sslpath}
            if [ -d ${sslpath}.bak ]; then
                mv ${sslpath}.bak ${sslpath}
            fi
        fi
    ;;
    *)
        echo "Unknown option '$1'"
        exit 1
    ;;
esac
