#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)


# Ensure that the script does not receive arguments.
if [ $# -ne 0 ]; then
    echo "E: The ${name} command takes no arguments"
    exit 1
fi

# Download PyEnv.
echo "Downloading PyEnv..."
pyenv_root="$(sh ${here}/manager info pyenv-root)"
wget -q https://github.com/pyenv/pyenv/archive/master.zip -O pyenv.zip

echo "Installing PyEnv..."
unzip -q pyenv.zip pyenv-master/* && mv pyenv-master "${pyenv_root}"
rm -f pyenv.zip

# Add PyEnv initialisation to profile.
echo "Configuring PyEnv..."
rc3=/etc/profile.d/03-set-pyenv.sh
echo "# Enable PyEnv environment" > ${rc3}
echo 'export PYENV_ROOT="'${pyenv_root}'"' >> ${rc3}
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ${rc3}
echo 'eval "$(pyenv init --path)"' >> ${rc3}
echo 'eval "$(pyenv init -)"' >> ${rc3}
echo "" >> ${rc3}

echo "Done!"
