#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)
alias manager="sh ${here}/manager"


_info_os_name() {
    echo $(grep ^ID= /etc/os-release | cut -d= -f 2 | sed -r 's/^"|"$//g')
}


_info_os_version() {
    echo $(grep ^VERSION_ID /etc/os-release | cut -d= -f 2 | sed -r 's/^"|"$//g')
}


_info_os_package_manager() {
    case "$(_info_os_name)" in
        ubuntu)
            echo apt-get
        ;;
        centos)
            echo yum
        ;;
        openSUSE*|SLES)
            echo zypper
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_hdf4() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "libhdf4-0 libhdf4-dev"
        ;;
        centos)
            echo "hdf hdf-devel"
        ;;
        *)
            echo "E:Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_hdf5() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "libhdf5-103 libhdf5-dev"
        ;;
        centos)
            echo "hdf5 hdf5-devel"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_blas() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "libblas3 libblas-dev"
        ;;
        centos)
            echo "blas blas-devel"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_lapack() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "liblapack3 liblapack-dev"
        ;;
        centos)
            echo "lapack lapack-devel"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_netcdf4() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "libnetcdf15 libnetcdf-dev"
        ;;
        centos)
            echo "netcdf netcdf-devel"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_matplotlib_dev() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "libfreetype-dev libpng-dev"
        ;;
        centos)
            echo "freetype-devel libpng-devel"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_openssl_root() {
    version=1.1.1k
    if [ ! -z "$1" ]; then
        version="$1"
    fi
    regex="1\.(0\.2[a-u]?|1\.1[a-k]?)"
    if [ -z $(echo "${version}" | grep -E "^${regex}$" || true) ]; then
        echo "E: Invalid openssl version '$1'"
        exit 1
    fi
    version_short=$(echo ${version} | sed -r 's|(([0-9]\.)+[0-9])[a-z]?|\1|g')
    echo /opt/openssl-${version_short}
}


_info_gcc_full() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "gcc g++ gfortran"
        ;;
        centos)
            echo "gcc gcc-c++ gcc-gfortran"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_pkg_config() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "pkg-config"
        ;;
        centos)
            echo "pkgconfig"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_pyenv_dev() {
    case "$(_info_os_name)" in
        ubuntu)
            echo "
                build-essential llvm libssl-dev tk-dev                        \
                libncursesw5-dev libreadline-dev libsqlite3-dev               \
                libffi-dev xz-utils zlib1g-dev libbz2-dev liblzma-dev
            " | xargs
        ;;
        centos)
            echo "
                @development findutils llvm openssl-devel readline-devel      \
                sqlite-devel libffi-devel xz-devel bzip2-devel zlib-devel
            " | xargs
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_pyenv_profile() {
    echo /etc/profile.d/01-set-pyenv.sh
}


_info_pyenv_root() {
    echo /usr/local/share/pyenv
}


case "$1" in
    blas|lapack|hdf4|hdf5|netcdf4|matplotlib-dev)
        _info_$(echo $1 | tr - _)
    ;;
    gcc-full|pkg-config)
        _info_$(echo $1 | tr - _)
    ;;
    openssl-root)
        shift
        _info_openssl_root $@
    ;;
    os-name|os-version|os-package-manager)
        _info_$(echo $1 | tr - _)
    ;;
    pyenv-dev|pyenv-profile|pyenv-root)
        _info_$(echo $1 | tr - _)
    ;;
    *)
        echo "E: Unknown option '$1'"
        exit 1
    ;;
esac
