#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)
find ${here}/ -name "manager" -exec chmod 755 {} \;
find ${here}/ -name "manager-*" -exec chmod 755 {} \;


# Main script.
option="$1"
case "${option}" in
    clean | disable | enable | info | install | remove | update)
        shift
        sh "${here}/${name}-${option}" $@
    ;;
    *)
        echo "Unknown option '${option}'"
        exit 1
    ;;
esac
