#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)
alias manager="sh ${here}/manager"


# Check number of arguments.
if [ $# -ne 1 ]; then
    echo "E: The ${name} command takes one argument"
    exit 1
fi

# Apply enabling.
case "$1" in
    openssl-1.0.2|openssl-1.1.1)
        sslpath=/usr/local/ssl
        prefix=$(manager info openssl-root $(echo $1 | cut -d- -f2))
        if [ -d ${sslpath} ]; then
            if [ ! -d ${sslpath}.bak -a ! -L ${sslpath} ]; then
                mv ${sslpath} ${sslpath}.bak
            else
                rm ${sslpath}
            fi
        fi
        ln -s ${prefix} ${sslpath}
    ;;
    *)
        echo "Unknown option '$1'"
        exit 1
    ;;
esac
