#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)


# Parse arguments.
if [ $# -eq 0 ]; then
    echo "E: The ${name} command takes at least one argument"
    exit 1
fi
first_repo_install=1
while [ $# -gt 0 ]; do
    case "$1" in
        openssl-1.0.2)
            sh ${here}/manager-install-openssl 1.0.2j
        ;;
        openssl-1.1.1)
            sh ${here}/manager-install-openssl 1.1.1k
        ;;
        *)
            pkgman=$(sh ${here}/manager info os-package-manager)
            case ${pkgman} in
                apt-get)
                    norecommends=--no-install-recommends
                ;;
                zypper)
                    norecommends=--no-recommends
                ;;
                *)
                    norecommends=
                ;;
            esac
            if [ ${first_repo_install} -eq 1 ]; then
                ${pkgman} update
                first_repo_install=0
            fi
            ${pkgman} install -y ${norecommends} $1
            ${pkgman} clean
        ;;
    esac
    shift
done
