#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)


_info_os_name() {
    echo $(grep ^NAME /etc/os-release | cut -d= -f 2 | sed -r 's/^"|"$//g')
}


_info_os_version() {
    echo $(grep ^VERSION_ID /etc/os-release | cut -d= -f 2 | sed -r 's/^"|"$//g')
}


_info_os_package_manager() {
    case "$(_info_os_name)" in
        Ubuntu)
            echo apt-get
        ;;
        CentOS|RedHat)
            echo yum
        ;;
        openSUSE*|SLES)
            echo zypper
        ;;
        *)
            echo "Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


# Parse arguments.
if [ $# -ne 1 ]; then
    echo "E: The ${name} command takes one argument"
    exit 1
fi
case "$1" in
    os-name)
        _info_os_name
    ;;
    os-version)
        _info_os_version
    ;;
    os-package-manager)
        _info_os_package_manager
    ;;
    *)
        echo "Unknown option '$1'"
        exit 1
    ;;
esac
